export const enums = {
  houseType: [
    "Home",
    "Apartment",
    "Condo",
    "Townhouse",
    "Duplex",
    "Mobile Home",
    "Cabin",
    "Loft",
    "Studio",
    "Others",
  ],
  currency: ["USD"],
  amenities: [
    "wifi",
    "tv",
    "ac",
    "kitchen",
    "parking",
    "pool",
    "gym",
    "hotTub",
    "fireplace",
    "washer",
    "dryer",
    "heating",
    "smokeDetector",
    "carbonMonoxideDetector",
    "firstAidKit",
    "fireExtinguisher",
  ],
  features: ["maxGuests", "bedrooms", "beds", "bathrooms"],
};
export default enums;
